name: Deploy Production

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'npm'
      - name: Create .env.production file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env.production
      - run: yarn ci
      - run: yarn run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            if [ ! -d "${{ secrets.REPO_NAME }}" ]; then
              echo "Cloning repository"
              git clone ${{ secrets.REPO_SSH }}
              echo "Cloning repository done"
              cd ~/${{ secrets.REPO_NAME }}
              echo "Installing dependencies"
              yarn ci --force
              echo "Installing dependencies done"
              echo "Setting up environment variables"
              echo "${{secrets.ENV_PRODUCTION}}" > .env.production
              echo "Setting up environment variables done"
              echo "Building application"
              yarn run build
              echo "Building application done"
              echo "Starting application"
              pm2 start ecosystem.config.js
              echo "Starting application done"
            else
              echo "Updating repository"
              cd ~/${{ secrets.REPO_NAME }}
              git fetch --all
              git reset --hard origin/main
              echo "Updating repository done"
              echo "Setting up environment variables"
              echo "${{secrets.ENV_PRODUCTION}}" > .env.production
              echo "Setting up environment variables done"
              echo "Installing dependencies"
              yarn ci --force
              echo "Installing dependencies done"
              echo "Building application"
              yarn run build
              echo "Building application done"
              echo "Restarting application"
              pm2 restart shop-ecom-fe
              echo "Restarting application done"
            fi
            pm2 save
      - name: Verify deployment
        run: |
          echo "Application deployed successfully!"
